services:
  app:
    build: .
    container_name: jitterbit_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      # AQUI: Estou usando 'root' e 'root' para garantir
      - DATABASE_URL=postgres://root:root@db:5432/produtos_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: jitterbit_db
    environment:
      # AQUI: Tem que ser IGUAL Ã  string acima
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: produtos_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: